// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: aoi.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ET_UNSPECIFIED EntityType = 0
	EntityType_ET_ROLE        EntityType = 1  // 角色
	EntityType_ET_RES         EntityType = 2  // 树木矿石等资源
	EntityType_ET_ANIMAL      EntityType = 3  // 动物
	EntityType_ET_BUILD       EntityType = 5  // 建筑
	EntityType_ET_FURNITURE   EntityType = 6  // 家具
	EntityType_ET_LAND        EntityType = 7  // 土地
	EntityType_ET_TREASURE    EntityType = 9  // 宝箱
	EntityType_ET_PET         EntityType = 10 // 宠物
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0:  "ET_UNSPECIFIED",
		1:  "ET_ROLE",
		2:  "ET_RES",
		3:  "ET_ANIMAL",
		5:  "ET_BUILD",
		6:  "ET_FURNITURE",
		7:  "ET_LAND",
		9:  "ET_TREASURE",
		10: "ET_PET",
	}
	EntityType_value = map[string]int32{
		"ET_UNSPECIFIED": 0,
		"ET_ROLE":        1,
		"ET_RES":         2,
		"ET_ANIMAL":      3,
		"ET_BUILD":       5,
		"ET_FURNITURE":   6,
		"ET_LAND":        7,
		"ET_TREASURE":    9,
		"ET_PET":         10,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_aoi_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_aoi_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{0}
}

type EntityLeaveReason int32

const (
	EntityLeaveReason_ELR_UNSPECIFIED   EntityLeaveReason = 0
	EntityLeaveReason_ELR_RES_COLLECTED EntityLeaveReason = 1 // 资源被开采完了
	EntityLeaveReason_ELR_LAND_DESTROY  EntityLeaveReason = 2 // 土地被占用了，修建了，然后需要销毁上面的资源和动物
	EntityLeaveReason_ELR_LEAVESPACE    EntityLeaveReason = 3 // 实体离开场景
)

// Enum value maps for EntityLeaveReason.
var (
	EntityLeaveReason_name = map[int32]string{
		0: "ELR_UNSPECIFIED",
		1: "ELR_RES_COLLECTED",
		2: "ELR_LAND_DESTROY",
		3: "ELR_LEAVESPACE",
	}
	EntityLeaveReason_value = map[string]int32{
		"ELR_UNSPECIFIED":   0,
		"ELR_RES_COLLECTED": 1,
		"ELR_LAND_DESTROY":  2,
		"ELR_LEAVESPACE":    3,
	}
)

func (x EntityLeaveReason) Enum() *EntityLeaveReason {
	p := new(EntityLeaveReason)
	*p = x
	return p
}

func (x EntityLeaveReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityLeaveReason) Descriptor() protoreflect.EnumDescriptor {
	return file_aoi_proto_enumTypes[1].Descriptor()
}

func (EntityLeaveReason) Type() protoreflect.EnumType {
	return &file_aoi_proto_enumTypes[1]
}

func (x EntityLeaveReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityLeaveReason.Descriptor instead.
func (EntityLeaveReason) EnumDescriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{1}
}

// 实体信息
type EntityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ  EntityType `protobuf:"varint,2,opt,name=typ,proto3,enum=protos.EntityType" json:"typ,omitempty"`
	Data []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EntityData) Reset() {
	*x = EntityData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityData) ProtoMessage() {}

func (x *EntityData) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityData.ProtoReflect.Descriptor instead.
func (*EntityData) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{0}
}

func (x *EntityData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityData) GetTyp() EntityType {
	if x != nil {
		return x.Typ
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *EntityData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 实体更新信息
type EntityUpdateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ  EntityType `protobuf:"varint,2,opt,name=typ,proto3,enum=protos.EntityType" json:"typ,omitempty"`
	Data []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EntityUpdateData) Reset() {
	*x = EntityUpdateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityUpdateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityUpdateData) ProtoMessage() {}

func (x *EntityUpdateData) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityUpdateData.ProtoReflect.Descriptor instead.
func (*EntityUpdateData) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{1}
}

func (x *EntityUpdateData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityUpdateData) GetTyp() EntityType {
	if x != nil {
		return x.Typ
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *EntityUpdateData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EntityEnterSight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ   EntityType `protobuf:"varint,2,opt,name=typ,proto3,enum=protos.EntityType" json:"typ,omitempty"`
	Data  []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Pos   *Vec3      `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Angle float32    `protobuf:"fixed32,5,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *EntityEnterSight) Reset() {
	*x = EntityEnterSight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityEnterSight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityEnterSight) ProtoMessage() {}

func (x *EntityEnterSight) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityEnterSight.ProtoReflect.Descriptor instead.
func (*EntityEnterSight) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{2}
}

func (x *EntityEnterSight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityEnterSight) GetTyp() EntityType {
	if x != nil {
		return x.Typ
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *EntityEnterSight) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EntityEnterSight) GetPos() *Vec3 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityEnterSight) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type EntityLeaveSight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ    EntityType        `protobuf:"varint,2,opt,name=typ,proto3,enum=protos.EntityType" json:"typ,omitempty"`
	Reason EntityLeaveReason `protobuf:"varint,3,opt,name=reason,proto3,enum=protos.EntityLeaveReason" json:"reason,omitempty"`
}

func (x *EntityLeaveSight) Reset() {
	*x = EntityLeaveSight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityLeaveSight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityLeaveSight) ProtoMessage() {}

func (x *EntityLeaveSight) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityLeaveSight.ProtoReflect.Descriptor instead.
func (*EntityLeaveSight) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{3}
}

func (x *EntityLeaveSight) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityLeaveSight) GetTyp() EntityType {
	if x != nil {
		return x.Typ
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *EntityLeaveSight) GetReason() EntityLeaveReason {
	if x != nil {
		return x.Reason
	}
	return EntityLeaveReason_ELR_UNSPECIFIED
}

// 实体更新信息
type BEntityUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*EntityUpdateData `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *BEntityUpdate) Reset() {
	*x = BEntityUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BEntityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BEntityUpdate) ProtoMessage() {}

func (x *BEntityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BEntityUpdate.ProtoReflect.Descriptor instead.
func (*BEntityUpdate) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{4}
}

func (x *BEntityUpdate) GetUpdates() []*EntityUpdateData {
	if x != nil {
		return x.Updates
	}
	return nil
}

type MoveTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Typ       EntityType `protobuf:"varint,2,opt,name=typ,proto3,enum=protos.EntityType" json:"typ,omitempty"`
	Cur       *Vec3      `protobuf:"bytes,3,opt,name=cur,proto3" json:"cur,omitempty"`
	Des       *Vec3      `protobuf:"bytes,4,opt,name=des,proto3" json:"des,omitempty"`
	Timestamp int64      `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 移动到目的地的时间，单位毫秒
}

func (x *MoveTo) Reset() {
	*x = MoveTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTo) ProtoMessage() {}

func (x *MoveTo) ProtoReflect() protoreflect.Message {
	mi := &file_aoi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTo.ProtoReflect.Descriptor instead.
func (*MoveTo) Descriptor() ([]byte, []int) {
	return file_aoi_proto_rawDescGZIP(), []int{5}
}

func (x *MoveTo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MoveTo) GetTyp() EntityType {
	if x != nil {
		return x.Typ
	}
	return EntityType_ET_UNSPECIFIED
}

func (x *MoveTo) GetCur() *Vec3 {
	if x != nil {
		return x.Cur
	}
	return nil
}

func (x *MoveTo) GetDes() *Vec3 {
	if x != nil {
		return x.Des
	}
	return nil
}

func (x *MoveTo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_aoi_proto protoreflect.FileDescriptor

var file_aoi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x6f, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x56, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x24, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x10, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a,
	0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03,
	0x74, 0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x03,
	0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x74,
	0x79, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63,
	0x33, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x7b, 0x0a, 0x10,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x03, 0x74, 0x79, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x0d, 0x42, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0x9c,
	0x01, 0x0a, 0x06, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x74, 0x79, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x74, 0x79, 0x70, 0x12,
	0x1e, 0x0a, 0x03, 0x63, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x63, 0x75, 0x72, 0x12,
	0x1e, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x92, 0x01,
	0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x45, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x45, 0x54, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x54, 0x5f,
	0x41, 0x4e, 0x49, 0x4d, 0x41, 0x4c, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x54, 0x5f, 0x42,
	0x55, 0x49, 0x4c, 0x44, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x54, 0x5f, 0x46, 0x55, 0x52,
	0x4e, 0x49, 0x54, 0x55, 0x52, 0x45, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x54, 0x5f, 0x4c,
	0x41, 0x4e, 0x44, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x54, 0x5f, 0x54, 0x52, 0x45, 0x41,
	0x53, 0x55, 0x52, 0x45, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x54, 0x5f, 0x50, 0x45, 0x54,
	0x10, 0x0a, 0x2a, 0x69, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4c, 0x52, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11,
	0x45, 0x4c, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x5f, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4c, 0x52, 0x5f, 0x4c, 0x41, 0x4e, 0x44, 0x5f,
	0x44, 0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4c, 0x52,
	0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x03, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_aoi_proto_rawDescOnce sync.Once
	file_aoi_proto_rawDescData = file_aoi_proto_rawDesc
)

func file_aoi_proto_rawDescGZIP() []byte {
	file_aoi_proto_rawDescOnce.Do(func() {
		file_aoi_proto_rawDescData = protoimpl.X.CompressGZIP(file_aoi_proto_rawDescData)
	})
	return file_aoi_proto_rawDescData
}

var file_aoi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aoi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aoi_proto_goTypes = []interface{}{
	(EntityType)(0),          // 0: protos.EntityType
	(EntityLeaveReason)(0),   // 1: protos.EntityLeaveReason
	(*EntityData)(nil),       // 2: protos.EntityData
	(*EntityUpdateData)(nil), // 3: protos.EntityUpdateData
	(*EntityEnterSight)(nil), // 4: protos.EntityEnterSight
	(*EntityLeaveSight)(nil), // 5: protos.EntityLeaveSight
	(*BEntityUpdate)(nil),    // 6: protos.BEntityUpdate
	(*MoveTo)(nil),           // 7: protos.MoveTo
	(*Vec3)(nil),             // 8: protos.Vec3
}
var file_aoi_proto_depIdxs = []int32{
	0,  // 0: protos.EntityData.typ:type_name -> protos.EntityType
	0,  // 1: protos.EntityUpdateData.typ:type_name -> protos.EntityType
	0,  // 2: protos.EntityEnterSight.typ:type_name -> protos.EntityType
	8,  // 3: protos.EntityEnterSight.pos:type_name -> protos.Vec3
	0,  // 4: protos.EntityLeaveSight.typ:type_name -> protos.EntityType
	1,  // 5: protos.EntityLeaveSight.reason:type_name -> protos.EntityLeaveReason
	3,  // 6: protos.BEntityUpdate.updates:type_name -> protos.EntityUpdateData
	0,  // 7: protos.MoveTo.typ:type_name -> protos.EntityType
	8,  // 8: protos.MoveTo.cur:type_name -> protos.Vec3
	8,  // 9: protos.MoveTo.des:type_name -> protos.Vec3
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_aoi_proto_init() }
func file_aoi_proto_init() {
	if File_aoi_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aoi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityUpdateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityEnterSight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityLeaveSight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BEntityUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aoi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aoi_proto_goTypes,
		DependencyIndexes: file_aoi_proto_depIdxs,
		EnumInfos:         file_aoi_proto_enumTypes,
		MessageInfos:      file_aoi_proto_msgTypes,
	}.Build()
	File_aoi_proto = out.File
	file_aoi_proto_rawDesc = nil
	file_aoi_proto_goTypes = nil
	file_aoi_proto_depIdxs = nil
}
