// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: apirpc.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 动物的锚点信息
type AnchorID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CityID int32  `protobuf:"varint,2,opt,name=cityID,proto3" json:"cityID,omitempty"`
}

func (x *AnchorID) Reset() {
	*x = AnchorID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnchorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorID) ProtoMessage() {}

func (x *AnchorID) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorID.ProtoReflect.Descriptor instead.
func (*AnchorID) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnchorID) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

type RPCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                                                                 // 玩家uid
	EntityID string            `protobuf:"bytes,2,opt,name=entityID,proto3" json:"entityID,omitempty"`                                                                                       // 玩家的角色ID
	SpaceID  string            `protobuf:"bytes,3,opt,name=spaceID,proto3" json:"spaceID,omitempty"`                                                                                         // 玩家在的space
	Extends  map[string]string `protobuf:"bytes,4,rep,name=extends,proto3" json:"extends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 附加字段
}

func (x *RPCReq) Reset() {
	*x = RPCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCReq) ProtoMessage() {}

func (x *RPCReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCReq.ProtoReflect.Descriptor instead.
func (*RPCReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RPCReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *RPCReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *RPCReq) GetExtends() map[string]string {
	if x != nil {
		return x.Extends
	}
	return nil
}

type CostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	EntityID string          `protobuf:"bytes,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Items    map[int32]int32 `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Index    int32           `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *CostReq) Reset() {
	*x = CostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReq) ProtoMessage() {}

func (x *CostReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReq.ProtoReflect.Descriptor instead.
func (*CostReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{2}
}

func (x *CostReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CostReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *CostReq) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CostReq) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type CostRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CostRsp) Reset() {
	*x = CostRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostRsp) ProtoMessage() {}

func (x *CostRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostRsp.ProtoReflect.Descriptor instead.
func (*CostRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{3}
}

//消耗装备耐久
type EquipCostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeaponType int32 `protobuf:"varint,1,opt,name=weaponType,proto3" json:"weaponType,omitempty"`
	WeaponQua  int32 `protobuf:"varint,2,opt,name=weaponQua,proto3" json:"weaponQua,omitempty"`
	WearVal    int32 `protobuf:"varint,3,opt,name=wearVal,proto3" json:"wearVal,omitempty"`
}

func (x *EquipCostReq) Reset() {
	*x = EquipCostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipCostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipCostReq) ProtoMessage() {}

func (x *EquipCostReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipCostReq.ProtoReflect.Descriptor instead.
func (*EquipCostReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{4}
}

func (x *EquipCostReq) GetWeaponType() int32 {
	if x != nil {
		return x.WeaponType
	}
	return 0
}

func (x *EquipCostReq) GetWeaponQua() int32 {
	if x != nil {
		return x.WeaponQua
	}
	return 0
}

func (x *EquipCostReq) GetWearVal() int32 {
	if x != nil {
		return x.WearVal
	}
	return 0
}

type EquipCostRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EquipCostRsp) Reset() {
	*x = EquipCostRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipCostRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipCostRsp) ProtoMessage() {}

func (x *EquipCostRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipCostRsp.ProtoReflect.Descriptor instead.
func (*EquipCostRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{5}
}

//消耗角色体力
type PowerCostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`  //玩家id
	Num int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"` //体力数量
}

func (x *PowerCostReq) Reset() {
	*x = PowerCostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerCostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerCostReq) ProtoMessage() {}

func (x *PowerCostReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerCostReq.ProtoReflect.Descriptor instead.
func (*PowerCostReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{6}
}

func (x *PowerCostReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PowerCostReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PowerCostRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PowerCostRsp) Reset() {
	*x = PowerCostRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerCostRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerCostRsp) ProtoMessage() {}

func (x *PowerCostRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerCostRsp.ProtoReflect.Descriptor instead.
func (*PowerCostRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{7}
}

//请求采集资源
type CollectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CsvID    int32  `protobuf:"varint,2,opt,name=csvID,proto3" json:"csvID,omitempty"`
	PlayerID string `protobuf:"bytes,3,opt,name=playerID,proto3" json:"playerID,omitempty"` //玩家id
}

func (x *CollectionReq) Reset() {
	*x = CollectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionReq) ProtoMessage() {}

func (x *CollectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionReq.ProtoReflect.Descriptor instead.
func (*CollectionReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{8}
}

func (x *CollectionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CollectionReq) GetCsvID() int32 {
	if x != nil {
		return x.CsvID
	}
	return 0
}

func (x *CollectionReq) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

//返回采集到的资源
type CollectionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastCollection bool  `protobuf:"varint,1,opt,name=lastCollection,proto3" json:"lastCollection,omitempty"`
	Pos            *Vec3 `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *CollectionRsp) Reset() {
	*x = CollectionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionRsp) ProtoMessage() {}

func (x *CollectionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionRsp.ProtoReflect.Descriptor instead.
func (*CollectionRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{9}
}

func (x *CollectionRsp) GetLastCollection() bool {
	if x != nil {
		return x.LastCollection
	}
	return false
}

func (x *CollectionRsp) GetPos() *Vec3 {
	if x != nil {
		return x.Pos
	}
	return nil
}

//返回新的宝藏点
type RspTreasureAnchor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Anchor map[string]int32 `protobuf:"bytes,1,rep,name=anchor,proto3" json:"anchor,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Flag   int32            `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"` // 1 = 加载的数据,2=刷新的数据
}

func (x *RspTreasureAnchor) Reset() {
	*x = RspTreasureAnchor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspTreasureAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspTreasureAnchor) ProtoMessage() {}

func (x *RspTreasureAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspTreasureAnchor.ProtoReflect.Descriptor instead.
func (*RspTreasureAnchor) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{10}
}

func (x *RspTreasureAnchor) GetAnchor() map[string]int32 {
	if x != nil {
		return x.Anchor
	}
	return nil
}

func (x *RspTreasureAnchor) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type RpcFeedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleID string `protobuf:"bytes,2,opt,name=roleID,proto3" json:"roleID,omitempty"`
	CsvID  int32  `protobuf:"varint,3,opt,name=csvID,proto3" json:"csvID,omitempty"`
}

func (x *RpcFeedReq) Reset() {
	*x = RpcFeedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcFeedReq) ProtoMessage() {}

func (x *RpcFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcFeedReq.ProtoReflect.Descriptor instead.
func (*RpcFeedReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{11}
}

func (x *RpcFeedReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcFeedReq) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *RpcFeedReq) GetCsvID() int32 {
	if x != nil {
		return x.CsvID
	}
	return 0
}

type RpcFeedRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sweet int32 `protobuf:"varint,1,opt,name=sweet,proto3" json:"sweet,omitempty"`
}

func (x *RpcFeedRsp) Reset() {
	*x = RpcFeedRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcFeedRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcFeedRsp) ProtoMessage() {}

func (x *RpcFeedRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcFeedRsp.ProtoReflect.Descriptor instead.
func (*RpcFeedRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{12}
}

func (x *RpcFeedRsp) GetSweet() int32 {
	if x != nil {
		return x.Sweet
	}
	return 0
}

type RpcCatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleID string `protobuf:"bytes,2,opt,name=roleID,proto3" json:"roleID,omitempty"`
	CsvID  int32  `protobuf:"varint,3,opt,name=csvID,proto3" json:"csvID,omitempty"`
}

func (x *RpcCatchReq) Reset() {
	*x = RpcCatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcCatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCatchReq) ProtoMessage() {}

func (x *RpcCatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCatchReq.ProtoReflect.Descriptor instead.
func (*RpcCatchReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{13}
}

func (x *RpcCatchReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcCatchReq) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *RpcCatchReq) GetCsvID() int32 {
	if x != nil {
		return x.CsvID
	}
	return 0
}

type RpcPeelSkinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleID string `protobuf:"bytes,2,opt,name=roleID,proto3" json:"roleID,omitempty"`
	CsvID  int32  `protobuf:"varint,3,opt,name=csvID,proto3" json:"csvID,omitempty"`
}

func (x *RpcPeelSkinReq) Reset() {
	*x = RpcPeelSkinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcPeelSkinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPeelSkinReq) ProtoMessage() {}

func (x *RpcPeelSkinReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPeelSkinReq.ProtoReflect.Descriptor instead.
func (*RpcPeelSkinReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{14}
}

func (x *RpcPeelSkinReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcPeelSkinReq) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *RpcPeelSkinReq) GetCsvID() int32 {
	if x != nil {
		return x.CsvID
	}
	return 0
}

//请求获取某buff数据
type RpcRoleBuffReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID string `protobuf:"bytes,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	BuffID   int32  `protobuf:"varint,2,opt,name=buffID,proto3" json:"buffID,omitempty"`
}

func (x *RpcRoleBuffReq) Reset() {
	*x = RpcRoleBuffReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcRoleBuffReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRoleBuffReq) ProtoMessage() {}

func (x *RpcRoleBuffReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRoleBuffReq.ProtoReflect.Descriptor instead.
func (*RpcRoleBuffReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{15}
}

func (x *RpcRoleBuffReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *RpcRoleBuffReq) GetBuffID() int32 {
	if x != nil {
		return x.BuffID
	}
	return 0
}

type RpcRoleBuffRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuffVal float64 `protobuf:"fixed64,1,opt,name=buffVal,proto3" json:"buffVal,omitempty"` // buff效果
}

func (x *RpcRoleBuffRsp) Reset() {
	*x = RpcRoleBuffRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcRoleBuffRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRoleBuffRsp) ProtoMessage() {}

func (x *RpcRoleBuffRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRoleBuffRsp.ProtoReflect.Descriptor instead.
func (*RpcRoleBuffRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{16}
}

func (x *RpcRoleBuffRsp) GetBuffVal() float64 {
	if x != nil {
		return x.BuffVal
	}
	return 0
}

type RpcListInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID string  `protobuf:"bytes,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Ids      []int32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *RpcListInt32) Reset() {
	*x = RpcListInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcListInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcListInt32) ProtoMessage() {}

func (x *RpcListInt32) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcListInt32.ProtoReflect.Descriptor instead.
func (*RpcListInt32) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{17}
}

func (x *RpcListInt32) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *RpcListInt32) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RpcMapInt2Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[int32]int32 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *RpcMapInt2Int) Reset() {
	*x = RpcMapInt2Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcMapInt2Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMapInt2Int) ProtoMessage() {}

func (x *RpcMapInt2Int) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMapInt2Int.ProtoReflect.Descriptor instead.
func (*RpcMapInt2Int) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{18}
}

func (x *RpcMapInt2Int) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type RpcStoreBuyGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsID int32 `protobuf:"varint,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	Num     int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *RpcStoreBuyGoodsReq) Reset() {
	*x = RpcStoreBuyGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcStoreBuyGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStoreBuyGoodsReq) ProtoMessage() {}

func (x *RpcStoreBuyGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStoreBuyGoodsReq.ProtoReflect.Descriptor instead.
func (*RpcStoreBuyGoodsReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{19}
}

func (x *RpcStoreBuyGoodsReq) GetGoodsID() int32 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *RpcStoreBuyGoodsReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RpcStoreBuyGoodsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsID int32 `protobuf:"varint,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	Num     int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	EndTime int64 `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
}

func (x *RpcStoreBuyGoodsRsp) Reset() {
	*x = RpcStoreBuyGoodsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcStoreBuyGoodsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStoreBuyGoodsRsp) ProtoMessage() {}

func (x *RpcStoreBuyGoodsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStoreBuyGoodsRsp.ProtoReflect.Descriptor instead.
func (*RpcStoreBuyGoodsRsp) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{20}
}

func (x *RpcStoreBuyGoodsRsp) GetGoodsID() int32 {
	if x != nil {
		return x.GoodsID
	}
	return 0
}

func (x *RpcStoreBuyGoodsRsp) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *RpcStoreBuyGoodsRsp) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CostAndGainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost *CostReq `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Gain *CostReq `protobuf:"bytes,2,opt,name=gain,proto3" json:"gain,omitempty"`
}

func (x *CostAndGainReq) Reset() {
	*x = CostAndGainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apirpc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostAndGainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostAndGainReq) ProtoMessage() {}

func (x *CostAndGainReq) ProtoReflect() protoreflect.Message {
	mi := &file_apirpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostAndGainReq.ProtoReflect.Descriptor instead.
func (*CostAndGainReq) Descriptor() ([]byte, []int) {
	return file_apirpc_proto_rawDescGZIP(), []int{21}
}

func (x *CostAndGainReq) GetCost() *CostReq {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *CostAndGainReq) GetGain() *CostReq {
	if x != nil {
		return x.Gain
	}
	return nil
}

var File_apirpc_proto protoreflect.FileDescriptor

var file_apirpc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x49, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x22, 0xc3, 0x01, 0x0a, 0x06, 0x52, 0x50, 0x43,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x07, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb9,
	0x01, 0x0a, 0x07, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x09, 0x0a, 0x07, 0x43, 0x6f,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x66, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x65, 0x61, 0x70, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x51,
	0x75, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x51, 0x75, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x65, 0x61, 0x72, 0x56, 0x61, 0x6c, 0x22, 0x0e, 0x0a,
	0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x32, 0x0a,
	0x0c, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x22, 0x51, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x57, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6c,
	0x61, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0xa1, 0x01,
	0x0a, 0x11, 0x52, 0x73, 0x70, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x41, 0x6e, 0x63,
	0x68, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x06, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x73, 0x70,
	0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x2e, 0x41,
	0x6e, 0x63, 0x68, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x61, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x4a, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44, 0x22, 0x22, 0x0a,
	0x0a, 0x52, 0x70, 0x63, 0x46, 0x65, 0x65, 0x64, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x77, 0x65, 0x65,
	0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x43, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x73, 0x76, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44, 0x22, 0x4e,
	0x0a, 0x0e, 0x52, 0x70, 0x63, 0x50, 0x65, 0x65, 0x6c, 0x53, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x73, 0x76, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x73, 0x76, 0x49, 0x44, 0x22, 0x44,
	0x0a, 0x0e, 0x52, 0x70, 0x63, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x75, 0x66, 0x66, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75,
	0x66, 0x66, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0e, 0x52, 0x70, 0x63, 0x52, 0x6f, 0x6c, 0x65, 0x42,
	0x75, 0x66, 0x66, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x66, 0x66, 0x56, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x62, 0x75, 0x66, 0x66, 0x56, 0x61, 0x6c,
	0x22, 0x3c, 0x0a, 0x0c, 0x52, 0x70, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x81,
	0x01, 0x0a, 0x0d, 0x52, 0x70, 0x63, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x74, 0x32, 0x49, 0x6e, 0x74,
	0x12, 0x36, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x61, 0x70, 0x49,
	0x6e, 0x74, 0x32, 0x49, 0x6e, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x41, 0x0a, 0x13, 0x52, 0x70, 0x63, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x75,
	0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x5b, 0x0a, 0x13, 0x52, 0x70, 0x63, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x42, 0x75, 0x79, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x43, 0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x47, 0x61, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x67, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x52, 0x04, 0x67, 0x61, 0x69, 0x6e, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_apirpc_proto_rawDescOnce sync.Once
	file_apirpc_proto_rawDescData = file_apirpc_proto_rawDesc
)

func file_apirpc_proto_rawDescGZIP() []byte {
	file_apirpc_proto_rawDescOnce.Do(func() {
		file_apirpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apirpc_proto_rawDescData)
	})
	return file_apirpc_proto_rawDescData
}

var file_apirpc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_apirpc_proto_goTypes = []interface{}{
	(*AnchorID)(nil),            // 0: protos.AnchorID
	(*RPCReq)(nil),              // 1: protos.RPCReq
	(*CostReq)(nil),             // 2: protos.CostReq
	(*CostRsp)(nil),             // 3: protos.CostRsp
	(*EquipCostReq)(nil),        // 4: protos.EquipCostReq
	(*EquipCostRsp)(nil),        // 5: protos.EquipCostRsp
	(*PowerCostReq)(nil),        // 6: protos.PowerCostReq
	(*PowerCostRsp)(nil),        // 7: protos.PowerCostRsp
	(*CollectionReq)(nil),       // 8: protos.CollectionReq
	(*CollectionRsp)(nil),       // 9: protos.CollectionRsp
	(*RspTreasureAnchor)(nil),   // 10: protos.RspTreasureAnchor
	(*RpcFeedReq)(nil),          // 11: protos.RpcFeedReq
	(*RpcFeedRsp)(nil),          // 12: protos.RpcFeedRsp
	(*RpcCatchReq)(nil),         // 13: protos.RpcCatchReq
	(*RpcPeelSkinReq)(nil),      // 14: protos.RpcPeelSkinReq
	(*RpcRoleBuffReq)(nil),      // 15: protos.RpcRoleBuffReq
	(*RpcRoleBuffRsp)(nil),      // 16: protos.RpcRoleBuffRsp
	(*RpcListInt32)(nil),        // 17: protos.RpcListInt32
	(*RpcMapInt2Int)(nil),       // 18: protos.RpcMapInt2Int
	(*RpcStoreBuyGoodsReq)(nil), // 19: protos.RpcStoreBuyGoodsReq
	(*RpcStoreBuyGoodsRsp)(nil), // 20: protos.RpcStoreBuyGoodsRsp
	(*CostAndGainReq)(nil),      // 21: protos.CostAndGainReq
	nil,                         // 22: protos.RPCReq.ExtendsEntry
	nil,                         // 23: protos.CostReq.ItemsEntry
	nil,                         // 24: protos.RspTreasureAnchor.AnchorEntry
	nil,                         // 25: protos.RpcMapInt2Int.ItemsEntry
	(*Vec3)(nil),                // 26: protos.Vec3
}
var file_apirpc_proto_depIdxs = []int32{
	22, // 0: protos.RPCReq.extends:type_name -> protos.RPCReq.ExtendsEntry
	23, // 1: protos.CostReq.items:type_name -> protos.CostReq.ItemsEntry
	26, // 2: protos.CollectionRsp.pos:type_name -> protos.Vec3
	24, // 3: protos.RspTreasureAnchor.anchor:type_name -> protos.RspTreasureAnchor.AnchorEntry
	25, // 4: protos.RpcMapInt2Int.items:type_name -> protos.RpcMapInt2Int.ItemsEntry
	2,  // 5: protos.CostAndGainReq.cost:type_name -> protos.CostReq
	2,  // 6: protos.CostAndGainReq.gain:type_name -> protos.CostReq
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_apirpc_proto_init() }
func file_apirpc_proto_init() {
	if File_apirpc_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apirpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnchorID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipCostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipCostRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerCostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerCostRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspTreasureAnchor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcFeedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcFeedRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcCatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcPeelSkinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcRoleBuffReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcRoleBuffRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcListInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcMapInt2Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcStoreBuyGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcStoreBuyGoodsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apirpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostAndGainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apirpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apirpc_proto_goTypes,
		DependencyIndexes: file_apirpc_proto_depIdxs,
		MessageInfos:      file_apirpc_proto_msgTypes,
	}.Build()
	File_apirpc_proto = out.File
	file_apirpc_proto_rawDesc = nil
	file_apirpc_proto_goTypes = nil
	file_apirpc_proto_depIdxs = nil
}
