// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: entity.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Vec2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{1}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 场景信息
type SpaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 场景id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 场景类型
	Kind int32 `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// 场景所在的serverID
	ServerID string `protobuf:"bytes,3,opt,name=serverID,proto3" json:"serverID,omitempty"`
}

func (x *SpaceInfo) Reset() {
	*x = SpaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceInfo) ProtoMessage() {}

func (x *SpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceInfo.ProtoReflect.Descriptor instead.
func (*SpaceInfo) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{2}
}

func (x *SpaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpaceInfo) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *SpaceInfo) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

type SyncPos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 实体id
	// TODO 这个 label 可以不要了
	Label string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // 实体label，实体的类型
	Cur   *Vec3   `protobuf:"bytes,3,opt,name=cur,proto3" json:"cur,omitempty"`     // 当前位置
	Yaw   float32 `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"`   // 绕Y轴旋转的弧度
}

func (x *SyncPos) Reset() {
	*x = SyncPos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPos) ProtoMessage() {}

func (x *SyncPos) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPos.ProtoReflect.Descriptor instead.
func (*SyncPos) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{3}
}

func (x *SyncPos) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncPos) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SyncPos) GetCur() *Vec3 {
	if x != nil {
		return x.Cur
	}
	return nil
}

func (x *SyncPos) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

type RspEnter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // code == Space_000 表示 进场景成功，其他表示失败
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RspEnter) Reset() {
	*x = RspEnter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspEnter) ProtoMessage() {}

func (x *RspEnter) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspEnter.ProtoReflect.Descriptor instead.
func (*RspEnter) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{4}
}

func (x *RspEnter) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RspEnter) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 实体所在的场景信息
type EntitySpaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 实体id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 实体类型
	Label string     `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Space *SpaceInfo `protobuf:"bytes,3,opt,name=space,proto3" json:"space,omitempty"`
}

func (x *EntitySpaceInfo) Reset() {
	*x = EntitySpaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitySpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySpaceInfo) ProtoMessage() {}

func (x *EntitySpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySpaceInfo.ProtoReflect.Descriptor instead.
func (*EntitySpaceInfo) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{5}
}

func (x *EntitySpaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntitySpaceInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EntitySpaceInfo) GetSpace() *SpaceInfo {
	if x != nil {
		return x.Space
	}
	return nil
}

// 多个实体的场景信息
type EntitiesSpaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*EntitySpaceInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *EntitiesSpaceInfo) Reset() {
	*x = EntitiesSpaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitiesSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitiesSpaceInfo) ProtoMessage() {}

func (x *EntitiesSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitiesSpaceInfo.ProtoReflect.Descriptor instead.
func (*EntitiesSpaceInfo) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{6}
}

func (x *EntitiesSpaceInfo) GetInfos() []*EntitySpaceInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 实体更新信息
type EntityUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// repeated Attr attrs = 3;
	Attrs map[string][]byte `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EntityUpdate) Reset() {
	*x = EntityUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityUpdate) ProtoMessage() {}

func (x *EntityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityUpdate.ProtoReflect.Descriptor instead.
func (*EntityUpdate) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{7}
}

func (x *EntityUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityUpdate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EntityUpdate) GetAttrs() map[string][]byte {
	if x != nil {
		return x.Attrs
	}
	return nil
}

// 实体id和类型，实体销毁或者离开场景时 只用发送这个信息给cellapp
type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label  string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Reason int32  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{8}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Entity) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 要销毁的实体列表
type DestroyEntities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *DestroyEntities) Reset() {
	*x = DestroyEntities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyEntities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyEntities) ProtoMessage() {}

func (x *DestroyEntities) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyEntities.ProtoReflect.Descriptor instead.
func (*DestroyEntities) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyEntities) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// 实体移动旋转
type EntityMoveRot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Pos   *Vec3  `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Rot   *Vec3  `protobuf:"bytes,4,opt,name=rot,proto3" json:"rot,omitempty"`
}

func (x *EntityMoveRot) Reset() {
	*x = EntityMoveRot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityMoveRot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoveRot) ProtoMessage() {}

func (x *EntityMoveRot) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoveRot.ProtoReflect.Descriptor instead.
func (*EntityMoveRot) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{10}
}

func (x *EntityMoveRot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityMoveRot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EntityMoveRot) GetPos() *Vec3 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntityMoveRot) GetRot() *Vec3 {
	if x != nil {
		return x.Rot
	}
	return nil
}

// 实体动作
type EntityAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label   string            `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	ActID   int32             `protobuf:"varint,4,opt,name=actID,proto3" json:"actID,omitempty"`
	Extends map[string]string `protobuf:"bytes,5,rep,name=extends,proto3" json:"extends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EntityAction) Reset() {
	*x = EntityAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAction) ProtoMessage() {}

func (x *EntityAction) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAction.ProtoReflect.Descriptor instead.
func (*EntityAction) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{11}
}

func (x *EntityAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityAction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EntityAction) GetActID() int32 {
	if x != nil {
		return x.ActID
	}
	return 0
}

func (x *EntityAction) GetExtends() map[string]string {
	if x != nil {
		return x.Extends
	}
	return nil
}

// MigrateEntityData 迁移的实体源信息
type SEntityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	EntityID    string `protobuf:"bytes,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel string `protobuf:"bytes,3,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
	// 该实体所在的base Server id， 如果为""，表示不在任何base server
	FromServerID string `protobuf:"bytes,4,opt,name=fromServerID,proto3" json:"fromServerID,omitempty"`
	EntityDatas  []byte `protobuf:"bytes,5,opt,name=entityDatas,proto3" json:"entityDatas,omitempty"`
	SpaceID      string `protobuf:"bytes,8,opt,name=spaceID,proto3" json:"spaceID,omitempty"`      // 实体当前所在的场景 spaceID
	SpaceKind    int32  `protobuf:"varint,9,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"` // 实体当前所在的场景 spaceKind
}

func (x *SEntityData) Reset() {
	*x = SEntityData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEntityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEntityData) ProtoMessage() {}

func (x *SEntityData) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEntityData.ProtoReflect.Descriptor instead.
func (*SEntityData) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{12}
}

func (x *SEntityData) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SEntityData) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *SEntityData) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

func (x *SEntityData) GetFromServerID() string {
	if x != nil {
		return x.FromServerID
	}
	return ""
}

func (x *SEntityData) GetEntityDatas() []byte {
	if x != nil {
		return x.EntityDatas
	}
	return nil
}

func (x *SEntityData) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *SEntityData) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

// 实体的 cell 部分的信息
type EntityCellInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     *SEntityData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	EnterPos *Vec3        `protobuf:"bytes,2,opt,name=enterPos,proto3" json:"enterPos,omitempty"`
	EnterRot *Vec3        `protobuf:"bytes,3,opt,name=enterRot,proto3" json:"enterRot,omitempty"`
}

func (x *EntityCellInfo) Reset() {
	*x = EntityCellInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityCellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityCellInfo) ProtoMessage() {}

func (x *EntityCellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityCellInfo.ProtoReflect.Descriptor instead.
func (*EntityCellInfo) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{13}
}

func (x *EntityCellInfo) GetData() *SEntityData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EntityCellInfo) GetEnterPos() *Vec3 {
	if x != nil {
		return x.EnterPos
	}
	return nil
}

func (x *EntityCellInfo) GetEnterRot() *Vec3 {
	if x != nil {
		return x.EnterRot
	}
	return nil
}

// 初始化数据时，同一个场景，进入大量实体
type ManyEntitiesEnterSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 静态实体
	Entities []*EntityCellInfo `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// 动物
	Animals        []*EntityCellInfo `protobuf:"bytes,2,rep,name=animals,proto3" json:"animals,omitempty"`
	EnterSpaceID   string            `protobuf:"bytes,3,opt,name=enterSpaceID,proto3" json:"enterSpaceID,omitempty"`
	EnterSpaceKind int32             `protobuf:"varint,4,opt,name=enterSpaceKind,proto3" json:"enterSpaceKind,omitempty"`
}

func (x *ManyEntitiesEnterSpaceReq) Reset() {
	*x = ManyEntitiesEnterSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManyEntitiesEnterSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyEntitiesEnterSpaceReq) ProtoMessage() {}

func (x *ManyEntitiesEnterSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyEntitiesEnterSpaceReq.ProtoReflect.Descriptor instead.
func (*ManyEntitiesEnterSpaceReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{14}
}

func (x *ManyEntitiesEnterSpaceReq) GetEntities() []*EntityCellInfo {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ManyEntitiesEnterSpaceReq) GetAnimals() []*EntityCellInfo {
	if x != nil {
		return x.Animals
	}
	return nil
}

func (x *ManyEntitiesEnterSpaceReq) GetEnterSpaceID() string {
	if x != nil {
		return x.EnterSpaceID
	}
	return ""
}

func (x *ManyEntitiesEnterSpaceReq) GetEnterSpaceKind() int32 {
	if x != nil {
		return x.EnterSpaceKind
	}
	return 0
}

// EnterSpaceReq 请求进入新场景 baseapp -> cellappmgr
type EnterSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID     string            `protobuf:"bytes,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel  string            `protobuf:"bytes,2,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
	FromServerID string            `protobuf:"bytes,3,opt,name=fromServerID,proto3" json:"fromServerID,omitempty"`
	SpaceID      string            `protobuf:"bytes,4,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	SpaceKind    int32             `protobuf:"varint,5,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	Pos          *Vec3             `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Time         int64             `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	IsSend       bool              `protobuf:"varint,8,opt,name=isSend,proto3" json:"isSend,omitempty"`
	ExtStrVal    map[string]string `protobuf:"bytes,9,rep,name=extStrVal,proto3" json:"extStrVal,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`   // 扩展字段，值为 string
	ExtIntVal    map[string]int32  `protobuf:"bytes,10,rep,name=extIntVal,proto3" json:"extIntVal,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 扩展字段，值为 int32
	ViewLayer    int32             `protobuf:"varint,11,opt,name=viewLayer,proto3" json:"viewLayer,omitempty"`                                                                                         // 进入场景时的视角
}

func (x *EnterSpaceReq) Reset() {
	*x = EnterSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSpaceReq) ProtoMessage() {}

func (x *EnterSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSpaceReq.ProtoReflect.Descriptor instead.
func (*EnterSpaceReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{15}
}

func (x *EnterSpaceReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *EnterSpaceReq) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

func (x *EnterSpaceReq) GetFromServerID() string {
	if x != nil {
		return x.FromServerID
	}
	return ""
}

func (x *EnterSpaceReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *EnterSpaceReq) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *EnterSpaceReq) GetPos() *Vec3 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EnterSpaceReq) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *EnterSpaceReq) GetIsSend() bool {
	if x != nil {
		return x.IsSend
	}
	return false
}

func (x *EnterSpaceReq) GetExtStrVal() map[string]string {
	if x != nil {
		return x.ExtStrVal
	}
	return nil
}

func (x *EnterSpaceReq) GetExtIntVal() map[string]int32 {
	if x != nil {
		return x.ExtIntVal
	}
	return nil
}

func (x *EnterSpaceReq) GetViewLayer() int32 {
	if x != nil {
		return x.ViewLayer
	}
	return 0
}

// RealEnterSpaceReq 请求进入场景返回 cellappmgr -> baseapp
type RealEnterSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID      string `protobuf:"bytes,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel   string `protobuf:"bytes,2,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
	SpaceServerID string `protobuf:"bytes,3,opt,name=spaceServerID,proto3" json:"spaceServerID,omitempty"`
	SpaceID       string `protobuf:"bytes,4,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	SpaceKind     int32  `protobuf:"varint,5,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	EnterPos      *Vec3  `protobuf:"bytes,6,opt,name=enterPos,proto3" json:"enterPos,omitempty"`
	ViewLayer     int32  `protobuf:"varint,7,opt,name=viewLayer,proto3" json:"viewLayer,omitempty"`
}

func (x *RealEnterSpaceReq) Reset() {
	*x = RealEnterSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealEnterSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealEnterSpaceReq) ProtoMessage() {}

func (x *RealEnterSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealEnterSpaceReq.ProtoReflect.Descriptor instead.
func (*RealEnterSpaceReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{16}
}

func (x *RealEnterSpaceReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *RealEnterSpaceReq) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

func (x *RealEnterSpaceReq) GetSpaceServerID() string {
	if x != nil {
		return x.SpaceServerID
	}
	return ""
}

func (x *RealEnterSpaceReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *RealEnterSpaceReq) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *RealEnterSpaceReq) GetEnterPos() *Vec3 {
	if x != nil {
		return x.EnterPos
	}
	return nil
}

func (x *RealEnterSpaceReq) GetViewLayer() int32 {
	if x != nil {
		return x.ViewLayer
	}
	return 0
}

// MigrateToReq 发给 对应的 space app 的消息  baseapp -> cellapp
type MigrateToCellReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityInfo     *EntityCellInfo `protobuf:"bytes,1,opt,name=entityInfo,proto3" json:"entityInfo,omitempty"`
	EnterSpaceID   string          `protobuf:"bytes,3,opt,name=enterSpaceID,proto3" json:"enterSpaceID,omitempty"`
	EnterSpaceKind int32           `protobuf:"varint,4,opt,name=enterSpaceKind,proto3" json:"enterSpaceKind,omitempty"`
	ViewLayer      int32           `protobuf:"varint,5,opt,name=viewLayer,proto3" json:"viewLayer,omitempty"`
}

func (x *MigrateToCellReq) Reset() {
	*x = MigrateToCellReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateToCellReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateToCellReq) ProtoMessage() {}

func (x *MigrateToCellReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateToCellReq.ProtoReflect.Descriptor instead.
func (*MigrateToCellReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{17}
}

func (x *MigrateToCellReq) GetEntityInfo() *EntityCellInfo {
	if x != nil {
		return x.EntityInfo
	}
	return nil
}

func (x *MigrateToCellReq) GetEnterSpaceID() string {
	if x != nil {
		return x.EnterSpaceID
	}
	return ""
}

func (x *MigrateToCellReq) GetEnterSpaceKind() int32 {
	if x != nil {
		return x.EnterSpaceKind
	}
	return 0
}

func (x *MigrateToCellReq) GetViewLayer() int32 {
	if x != nil {
		return x.ViewLayer
	}
	return 0
}

// 空间创建完成后的通知
type SpaceLoadedNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseServerID string `protobuf:"bytes,1,opt,name=baseServerID,proto3" json:"baseServerID,omitempty"`
	CellServerID string `protobuf:"bytes,2,opt,name=cellServerID,proto3" json:"cellServerID,omitempty"`
	SpaceID      string `protobuf:"bytes,3,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	SpaceKind    int32  `protobuf:"varint,4,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
}

func (x *SpaceLoadedNotify) Reset() {
	*x = SpaceLoadedNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceLoadedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceLoadedNotify) ProtoMessage() {}

func (x *SpaceLoadedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceLoadedNotify.ProtoReflect.Descriptor instead.
func (*SpaceLoadedNotify) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{18}
}

func (x *SpaceLoadedNotify) GetBaseServerID() string {
	if x != nil {
		return x.BaseServerID
	}
	return ""
}

func (x *SpaceLoadedNotify) GetCellServerID() string {
	if x != nil {
		return x.CellServerID
	}
	return ""
}

func (x *SpaceLoadedNotify) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *SpaceLoadedNotify) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

// 请求创建场景
type CreateBaseSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 场景 ID
	SpaceID string `protobuf:"bytes,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	// 场景类型
	SpaceKind int32 `protobuf:"varint,2,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	// 在哪个 cellapp 上，放置该场景的实体
	CellServerID string `protobuf:"bytes,3,opt,name=cellServerID,proto3" json:"cellServerID,omitempty"`
	// 扩展字段
	Extra map[string]string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateBaseSpaceReq) Reset() {
	*x = CreateBaseSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBaseSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBaseSpaceReq) ProtoMessage() {}

func (x *CreateBaseSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBaseSpaceReq.ProtoReflect.Descriptor instead.
func (*CreateBaseSpaceReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{19}
}

func (x *CreateBaseSpaceReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *CreateBaseSpaceReq) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *CreateBaseSpaceReq) GetCellServerID() string {
	if x != nil {
		return x.CellServerID
	}
	return ""
}

func (x *CreateBaseSpaceReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type CreateCellSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 场景 ID
	SpaceID string `protobuf:"bytes,1,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	// 场景类型
	SpaceKind int32 `protobuf:"varint,2,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	// 在哪个 baseapp 上，放置该场景的实体
	BaseServerID string `protobuf:"bytes,3,opt,name=baseServerID,proto3" json:"baseServerID,omitempty"`
	// 扩展字段
	Extra map[string]string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateCellSpaceReq) Reset() {
	*x = CreateCellSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCellSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellSpaceReq) ProtoMessage() {}

func (x *CreateCellSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellSpaceReq.ProtoReflect.Descriptor instead.
func (*CreateCellSpaceReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{20}
}

func (x *CreateCellSpaceReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *CreateCellSpaceReq) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *CreateCellSpaceReq) GetBaseServerID() string {
	if x != nil {
		return x.BaseServerID
	}
	return ""
}

func (x *CreateCellSpaceReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type EnterSpaceResultNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok            bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrCode       string `protobuf:"bytes,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg        string `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SpaceID       string `protobuf:"bytes,4,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	SpaceKind     int32  `protobuf:"varint,5,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	SpaceServerID string `protobuf:"bytes,6,opt,name=spaceServerID,proto3" json:"spaceServerID,omitempty"`
	EntityID      string `protobuf:"bytes,7,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel   string `protobuf:"bytes,8,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
}

func (x *EnterSpaceResultNotify) Reset() {
	*x = EnterSpaceResultNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSpaceResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSpaceResultNotify) ProtoMessage() {}

func (x *EnterSpaceResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSpaceResultNotify.ProtoReflect.Descriptor instead.
func (*EnterSpaceResultNotify) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{21}
}

func (x *EnterSpaceResultNotify) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EnterSpaceResultNotify) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *EnterSpaceResultNotify) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *EnterSpaceResultNotify) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *EnterSpaceResultNotify) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *EnterSpaceResultNotify) GetSpaceServerID() string {
	if x != nil {
		return x.SpaceServerID
	}
	return ""
}

func (x *EnterSpaceResultNotify) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *EnterSpaceResultNotify) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

// 请求加载城市实体
type LoadRegionEntityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionServerID string `protobuf:"bytes,1,opt,name=regionServerID,proto3" json:"regionServerID,omitempty"`
	//请求序号
	SeqID int64 `protobuf:"varint,2,opt,name=seqID,proto3" json:"seqID,omitempty"`
}

func (x *LoadRegionEntityReq) Reset() {
	*x = LoadRegionEntityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRegionEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRegionEntityReq) ProtoMessage() {}

func (x *LoadRegionEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRegionEntityReq.ProtoReflect.Descriptor instead.
func (*LoadRegionEntityReq) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{22}
}

func (x *LoadRegionEntityReq) GetRegionServerID() string {
	if x != nil {
		return x.RegionServerID
	}
	return ""
}

func (x *LoadRegionEntityReq) GetSeqID() int64 {
	if x != nil {
		return x.SeqID
	}
	return 0
}

// 应答加载城市实体
type LoadRegionEntityNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellServerID string `protobuf:"bytes,1,opt,name=cellServerID,proto3" json:"cellServerID,omitempty"`
	//请求包发过来的序号
	SeqID int64 `protobuf:"varint,2,opt,name=seqID,proto3" json:"seqID,omitempty"`
	// 0: 不同意加载实体到该cellapp； 1：同意加载到该cellapp
	LoadFlag int32 `protobuf:"varint,3,opt,name=loadFlag,proto3" json:"loadFlag,omitempty"`
}

func (x *LoadRegionEntityNotify) Reset() {
	*x = LoadRegionEntityNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRegionEntityNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRegionEntityNotify) ProtoMessage() {}

func (x *LoadRegionEntityNotify) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRegionEntityNotify.ProtoReflect.Descriptor instead.
func (*LoadRegionEntityNotify) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{23}
}

func (x *LoadRegionEntityNotify) GetCellServerID() string {
	if x != nil {
		return x.CellServerID
	}
	return ""
}

func (x *LoadRegionEntityNotify) GetSeqID() int64 {
	if x != nil {
		return x.SeqID
	}
	return 0
}

func (x *LoadRegionEntityNotify) GetLoadFlag() int32 {
	if x != nil {
		return x.LoadFlag
	}
	return 0
}

// 应答: 请求创建场景(若当前baseapp需要的话)
type CreateSpaceIfNeedNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseServerID string `protobuf:"bytes,1,opt,name=baseServerID,proto3" json:"baseServerID,omitempty"`
	CellServerID string `protobuf:"bytes,2,opt,name=cellServerID,proto3" json:"cellServerID,omitempty"`
	SpaceID      string `protobuf:"bytes,3,opt,name=spaceID,proto3" json:"spaceID,omitempty"`
	SpaceKind    int32  `protobuf:"varint,4,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`
	// 0: 未创建；1：已创建；2：无需创建
	MasterSpaceFlag int32 `protobuf:"varint,5,opt,name=masterSpaceFlag,proto3" json:"masterSpaceFlag,omitempty"`
}

func (x *CreateSpaceIfNeedNotify) Reset() {
	*x = CreateSpaceIfNeedNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceIfNeedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceIfNeedNotify) ProtoMessage() {}

func (x *CreateSpaceIfNeedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_entity_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceIfNeedNotify.ProtoReflect.Descriptor instead.
func (*CreateSpaceIfNeedNotify) Descriptor() ([]byte, []int) {
	return file_entity_proto_rawDescGZIP(), []int{24}
}

func (x *CreateSpaceIfNeedNotify) GetBaseServerID() string {
	if x != nil {
		return x.BaseServerID
	}
	return ""
}

func (x *CreateSpaceIfNeedNotify) GetCellServerID() string {
	if x != nil {
		return x.CellServerID
	}
	return ""
}

func (x *CreateSpaceIfNeedNotify) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *CreateSpaceIfNeedNotify) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *CreateSpaceIfNeedNotify) GetMasterSpaceFlag() int32 {
	if x != nil {
		return x.MasterSpaceFlag
	}
	return 0
}

var File_entity_proto protoreflect.FileDescriptor

var file_entity_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x30, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x33, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x22, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x32,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x4b, 0x0a, 0x09,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0x61, 0x0a, 0x07, 0x53, 0x79, 0x6e,
	0x63, 0x50, 0x6f, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x03, 0x63, 0x75,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x63, 0x75, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61,
	0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x22, 0x30, 0x0a, 0x08,
	0x52, 0x73, 0x70, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x60,
	0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x42, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x35, 0x0a, 0x05, 0x61,
	0x74, 0x74, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61, 0x74, 0x74,
	0x72, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x46, 0x0a, 0x06,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x22, 0x75, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x76,
	0x65, 0x52, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x03, 0x70, 0x6f,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x03, 0x72, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x72, 0x6f, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x0c, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x61, 0x63, 0x74, 0x49, 0x44, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xe1, 0x01, 0x0a, 0x0b, 0x53, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72,
	0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43,
	0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33,
	0x52, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x6f, 0x74, 0x22, 0xcd, 0x01, 0x0a, 0x19, 0x4d, 0x61, 0x6e, 0x79, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x32, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x22, 0x97, 0x04, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x1e, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x03, 0x70, 0x6f, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x42, 0x0a, 0x09,
	0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x53, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x65, 0x78, 0x74, 0x53, 0x74, 0x72, 0x56, 0x61, 0x6c,
	0x12, 0x42, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x49, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x65, 0x78, 0x74, 0x49, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x65, 0x77, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x1a, 0x3c, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x53, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x3c, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x49, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf7,
	0x01, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33,
	0x52, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69,
	0x65, 0x77, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76,
	0x69, 0x65, 0x77, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x36, 0x0a,
	0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x43, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x69, 0x65, 0x77, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x93, 0x01, 0x0a, 0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x65, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0xe7, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x4b, 0x69, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x65, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x3b, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xe7, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x3b, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a,
	0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf6, 0x01, 0x0a, 0x16, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x22, 0x53, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x44, 0x22, 0x6e, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x22, 0xc3, 0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x66, 0x4e, 0x65, 0x65, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_entity_proto_rawDescOnce sync.Once
	file_entity_proto_rawDescData = file_entity_proto_rawDesc
)

func file_entity_proto_rawDescGZIP() []byte {
	file_entity_proto_rawDescOnce.Do(func() {
		file_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_proto_rawDescData)
	})
	return file_entity_proto_rawDescData
}

var file_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_entity_proto_goTypes = []interface{}{
	(*Vec3)(nil),                      // 0: protos.Vec3
	(*Vec2)(nil),                      // 1: protos.Vec2
	(*SpaceInfo)(nil),                 // 2: protos.SpaceInfo
	(*SyncPos)(nil),                   // 3: protos.SyncPos
	(*RspEnter)(nil),                  // 4: protos.RspEnter
	(*EntitySpaceInfo)(nil),           // 5: protos.EntitySpaceInfo
	(*EntitiesSpaceInfo)(nil),         // 6: protos.EntitiesSpaceInfo
	(*EntityUpdate)(nil),              // 7: protos.EntityUpdate
	(*Entity)(nil),                    // 8: protos.Entity
	(*DestroyEntities)(nil),           // 9: protos.DestroyEntities
	(*EntityMoveRot)(nil),             // 10: protos.EntityMoveRot
	(*EntityAction)(nil),              // 11: protos.EntityAction
	(*SEntityData)(nil),               // 12: protos.SEntityData
	(*EntityCellInfo)(nil),            // 13: protos.EntityCellInfo
	(*ManyEntitiesEnterSpaceReq)(nil), // 14: protos.ManyEntitiesEnterSpaceReq
	(*EnterSpaceReq)(nil),             // 15: protos.EnterSpaceReq
	(*RealEnterSpaceReq)(nil),         // 16: protos.RealEnterSpaceReq
	(*MigrateToCellReq)(nil),          // 17: protos.MigrateToCellReq
	(*SpaceLoadedNotify)(nil),         // 18: protos.SpaceLoadedNotify
	(*CreateBaseSpaceReq)(nil),        // 19: protos.CreateBaseSpaceReq
	(*CreateCellSpaceReq)(nil),        // 20: protos.CreateCellSpaceReq
	(*EnterSpaceResultNotify)(nil),    // 21: protos.EnterSpaceResultNotify
	(*LoadRegionEntityReq)(nil),       // 22: protos.LoadRegionEntityReq
	(*LoadRegionEntityNotify)(nil),    // 23: protos.LoadRegionEntityNotify
	(*CreateSpaceIfNeedNotify)(nil),   // 24: protos.CreateSpaceIfNeedNotify
	nil,                               // 25: protos.EntityUpdate.AttrsEntry
	nil,                               // 26: protos.EntityAction.ExtendsEntry
	nil,                               // 27: protos.EnterSpaceReq.ExtStrValEntry
	nil,                               // 28: protos.EnterSpaceReq.ExtIntValEntry
	nil,                               // 29: protos.CreateBaseSpaceReq.ExtraEntry
	nil,                               // 30: protos.CreateCellSpaceReq.ExtraEntry
}
var file_entity_proto_depIdxs = []int32{
	0,  // 0: protos.SyncPos.cur:type_name -> protos.Vec3
	2,  // 1: protos.EntitySpaceInfo.space:type_name -> protos.SpaceInfo
	5,  // 2: protos.EntitiesSpaceInfo.infos:type_name -> protos.EntitySpaceInfo
	25, // 3: protos.EntityUpdate.attrs:type_name -> protos.EntityUpdate.AttrsEntry
	8,  // 4: protos.DestroyEntities.entities:type_name -> protos.Entity
	0,  // 5: protos.EntityMoveRot.pos:type_name -> protos.Vec3
	0,  // 6: protos.EntityMoveRot.rot:type_name -> protos.Vec3
	26, // 7: protos.EntityAction.extends:type_name -> protos.EntityAction.ExtendsEntry
	12, // 8: protos.EntityCellInfo.data:type_name -> protos.SEntityData
	0,  // 9: protos.EntityCellInfo.enterPos:type_name -> protos.Vec3
	0,  // 10: protos.EntityCellInfo.enterRot:type_name -> protos.Vec3
	13, // 11: protos.ManyEntitiesEnterSpaceReq.entities:type_name -> protos.EntityCellInfo
	13, // 12: protos.ManyEntitiesEnterSpaceReq.animals:type_name -> protos.EntityCellInfo
	0,  // 13: protos.EnterSpaceReq.pos:type_name -> protos.Vec3
	27, // 14: protos.EnterSpaceReq.extStrVal:type_name -> protos.EnterSpaceReq.ExtStrValEntry
	28, // 15: protos.EnterSpaceReq.extIntVal:type_name -> protos.EnterSpaceReq.ExtIntValEntry
	0,  // 16: protos.RealEnterSpaceReq.enterPos:type_name -> protos.Vec3
	13, // 17: protos.MigrateToCellReq.entityInfo:type_name -> protos.EntityCellInfo
	29, // 18: protos.CreateBaseSpaceReq.extra:type_name -> protos.CreateBaseSpaceReq.ExtraEntry
	30, // 19: protos.CreateCellSpaceReq.extra:type_name -> protos.CreateCellSpaceReq.ExtraEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_entity_proto_init() }
func file_entity_proto_init() {
	if File_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspEnter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitySpaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitiesSpaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyEntities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityMoveRot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEntityData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityCellInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManyEntitiesEnterSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealEnterSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateToCellReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceLoadedNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBaseSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCellSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSpaceResultNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRegionEntityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRegionEntityNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entity_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceIfNeedNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_proto_goTypes,
		DependencyIndexes: file_entity_proto_depIdxs,
		MessageInfos:      file_entity_proto_msgTypes,
	}.Build()
	File_entity_proto = out.File
	file_entity_proto_rawDesc = nil
	file_entity_proto_goTypes = nil
	file_entity_proto_depIdxs = nil
}
