// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: landrpc.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 实体的操作枚举
type EOp int32

const (
	EOp_EOP_UNSPECIFIED EOp = 0
	EOp_EOP_CREATE      EOp = 1
	EOp_EOP_UPDATE      EOp = 2
	EOp_EOP_DESTROY     EOp = 3
	EOp_EOP_LEVEL_UP    EOp = 4
)

// Enum value maps for EOp.
var (
	EOp_name = map[int32]string{
		0: "EOP_UNSPECIFIED",
		1: "EOP_CREATE",
		2: "EOP_UPDATE",
		3: "EOP_DESTROY",
		4: "EOP_LEVEL_UP",
	}
	EOp_value = map[string]int32{
		"EOP_UNSPECIFIED": 0,
		"EOP_CREATE":      1,
		"EOP_UPDATE":      2,
		"EOP_DESTROY":     3,
		"EOP_LEVEL_UP":    4,
	}
)

func (x EOp) Enum() *EOp {
	p := new(EOp)
	*p = x
	return p
}

func (x EOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EOp) Descriptor() protoreflect.EnumDescriptor {
	return file_landrpc_proto_enumTypes[0].Descriptor()
}

func (EOp) Type() protoreflect.EnumType {
	return &file_landrpc_proto_enumTypes[0]
}

func (x EOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EOp.Descriptor instead.
func (EOp) EnumDescriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{0}
}

type RPCCityTown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID int32 `protobuf:"varint,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	TownID int32 `protobuf:"varint,2,opt,name=townID,proto3" json:"townID,omitempty"`
}

func (x *RPCCityTown) Reset() {
	*x = RPCCityTown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCCityTown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCCityTown) ProtoMessage() {}

func (x *RPCCityTown) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCCityTown.ProtoReflect.Descriptor instead.
func (*RPCCityTown) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCCityTown) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

func (x *RPCCityTown) GetTownID() int32 {
	if x != nil {
		return x.TownID
	}
	return 0
}

type RPCCreateInTown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID int32 `protobuf:"varint,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	TownID int32 `protobuf:"varint,2,opt,name=townID,proto3" json:"townID,omitempty"`
}

func (x *RPCCreateInTown) Reset() {
	*x = RPCCreateInTown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCCreateInTown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCCreateInTown) ProtoMessage() {}

func (x *RPCCreateInTown) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCCreateInTown.ProtoReflect.Descriptor instead.
func (*RPCCreateInTown) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCCreateInTown) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

func (x *RPCCreateInTown) GetTownID() int32 {
	if x != nil {
		return x.TownID
	}
	return 0
}

type RPCCreateInTownRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos    *Vec2 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`        // 返回玩家得出生点
	Number int32 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"` // 当前玩家是该城镇得第几个玩家
}

func (x *RPCCreateInTownRsp) Reset() {
	*x = RPCCreateInTownRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCCreateInTownRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCCreateInTownRsp) ProtoMessage() {}

func (x *RPCCreateInTownRsp) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCCreateInTownRsp.ProtoReflect.Descriptor instead.
func (*RPCCreateInTownRsp) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{2}
}

func (x *RPCCreateInTownRsp) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *RPCCreateInTownRsp) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type RPCEntityTransferInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家信息
	Uid          string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                   // 玩家uid
	RoleID       string `protobuf:"bytes,2,opt,name=roleID,proto3" json:"roleID,omitempty"`             // 角色id
	BaseServerID string `protobuf:"bytes,3,opt,name=baseServerID,proto3" json:"baseServerID,omitempty"` // 角色所在的base server id
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                 // 角色名字
	Head         string `protobuf:"bytes,5,opt,name=head,proto3" json:"head,omitempty"`                 // 角色头像
	CityID       int32  `protobuf:"varint,6,opt,name=cityID,proto3" json:"cityID,omitempty"`            // 角色所在的城市id
	SpaceID      string `protobuf:"bytes,7,opt,name=spaceID,proto3" json:"spaceID,omitempty"`           // 角色在哪个场景 ID
	SpaceKind    int32  `protobuf:"varint,8,opt,name=spaceKind,proto3" json:"spaceKind,omitempty"`      // 角色在哪种场景
	TownID       int32  `protobuf:"varint,9,opt,name=townID,proto3" json:"townID,omitempty"`            // 角色所在的镇 id
}

func (x *RPCEntityTransferInfo) Reset() {
	*x = RPCEntityTransferInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEntityTransferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEntityTransferInfo) ProtoMessage() {}

func (x *RPCEntityTransferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEntityTransferInfo.ProtoReflect.Descriptor instead.
func (*RPCEntityTransferInfo) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{3}
}

func (x *RPCEntityTransferInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetBaseServerID() string {
	if x != nil {
		return x.BaseServerID
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

func (x *RPCEntityTransferInfo) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *RPCEntityTransferInfo) GetSpaceKind() int32 {
	if x != nil {
		return x.SpaceKind
	}
	return 0
}

func (x *RPCEntityTransferInfo) GetTownID() int32 {
	if x != nil {
		return x.TownID
	}
	return 0
}

// call 某个实体的方法，
type RPCEntityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 玩家透传信息
	RoleTransfer *RPCEntityTransferInfo `protobuf:"bytes,1,opt,name=roleTransfer,proto3" json:"roleTransfer,omitempty"`
	// 哪个实体
	EntityID    string `protobuf:"bytes,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel string `protobuf:"bytes,3,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
	// 需要传递的参数
	Extend1 map[string]int32  `protobuf:"bytes,4,rep,name=extend1,proto3" json:"extend1,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Extend2 map[string]string `protobuf:"bytes,5,rep,name=extend2,proto3" json:"extend2,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Extend3 *anypb.Any        `protobuf:"bytes,6,opt,name=extend3,proto3" json:"extend3,omitempty"`
}

func (x *RPCEntityReq) Reset() {
	*x = RPCEntityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEntityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEntityReq) ProtoMessage() {}

func (x *RPCEntityReq) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEntityReq.ProtoReflect.Descriptor instead.
func (*RPCEntityReq) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{4}
}

func (x *RPCEntityReq) GetRoleTransfer() *RPCEntityTransferInfo {
	if x != nil {
		return x.RoleTransfer
	}
	return nil
}

func (x *RPCEntityReq) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *RPCEntityReq) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

func (x *RPCEntityReq) GetExtend1() map[string]int32 {
	if x != nil {
		return x.Extend1
	}
	return nil
}

func (x *RPCEntityReq) GetExtend2() map[string]string {
	if x != nil {
		return x.Extend2
	}
	return nil
}

func (x *RPCEntityReq) GetExtend3() *anypb.Any {
	if x != nil {
		return x.Extend3
	}
	return nil
}

// call 某个场景的方法
type RPCSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Baseinfo *RPCEntityReq `protobuf:"bytes,1,opt,name=baseinfo,proto3" json:"baseinfo,omitempty"`
	// 转发给哪个场景的哪个路由
	ToSpaceID   string `protobuf:"bytes,2,opt,name=toSpaceID,proto3" json:"toSpaceID,omitempty"`
	ToSpaceKind int32  `protobuf:"varint,3,opt,name=toSpaceKind,proto3" json:"toSpaceKind,omitempty"`
	Router      string `protobuf:"bytes,4,opt,name=router,proto3" json:"router,omitempty"`
}

func (x *RPCSpaceReq) Reset() {
	*x = RPCSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCSpaceReq) ProtoMessage() {}

func (x *RPCSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCSpaceReq.ProtoReflect.Descriptor instead.
func (*RPCSpaceReq) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{5}
}

func (x *RPCSpaceReq) GetBaseinfo() *RPCEntityReq {
	if x != nil {
		return x.Baseinfo
	}
	return nil
}

func (x *RPCSpaceReq) GetToSpaceID() string {
	if x != nil {
		return x.ToSpaceID
	}
	return ""
}

func (x *RPCSpaceReq) GetToSpaceKind() int32 {
	if x != nil {
		return x.ToSpaceKind
	}
	return 0
}

func (x *RPCSpaceReq) GetRouter() string {
	if x != nil {
		return x.Router
	}
	return ""
}

type Consume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds    int32           `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`                                                                                      // 需要耗时多少秒
	Items      map[int32]int32 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 需要哪几类资源
	Op         EOp             `protobuf:"varint,3,opt,name=op,proto3,enum=protos.EOp" json:"op,omitempty"`                                                                                // 哪种操作的消耗计算
	Workers    int32           `protobuf:"varint,4,opt,name=workers,proto3" json:"workers,omitempty"`                                                                                      // 需要工人数
	RecruitId  int32           `protobuf:"varint,5,opt,name=recruitId,proto3" json:"recruitId,omitempty"`                                                                                  // 需要哪种雇佣
	SkillLevel int32           `protobuf:"varint,6,opt,name=skillLevel,proto3" json:"skillLevel,omitempty"`                                                                                // 工人技能等级
}

func (x *Consume) Reset() {
	*x = Consume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{6}
}

func (x *Consume) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Consume) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Consume) GetOp() EOp {
	if x != nil {
		return x.Op
	}
	return EOp_EOP_UNSPECIFIED
}

func (x *Consume) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *Consume) GetRecruitId() int32 {
	if x != nil {
		return x.RecruitId
	}
	return 0
}

func (x *Consume) GetSkillLevel() int32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

type RpcChangeGroundReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID     string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty"`          //角色id
	LandID     int32  `protobuf:"varint,2,opt,name=landID,proto3" json:"landID,omitempty"`         //土地id
	DecorateID int32  `protobuf:"varint,3,opt,name=decorateID,proto3" json:"decorateID,omitempty"` //基建id
	CityID     int32  `protobuf:"varint,4,opt,name=cityID,proto3" json:"cityID,omitempty"`         //城市id
}

func (x *RpcChangeGroundReq) Reset() {
	*x = RpcChangeGroundReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_landrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcChangeGroundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcChangeGroundReq) ProtoMessage() {}

func (x *RpcChangeGroundReq) ProtoReflect() protoreflect.Message {
	mi := &file_landrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcChangeGroundReq.ProtoReflect.Descriptor instead.
func (*RpcChangeGroundReq) Descriptor() ([]byte, []int) {
	return file_landrpc_proto_rawDescGZIP(), []int{7}
}

func (x *RpcChangeGroundReq) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *RpcChangeGroundReq) GetLandID() int32 {
	if x != nil {
		return x.LandID
	}
	return 0
}

func (x *RpcChangeGroundReq) GetDecorateID() int32 {
	if x != nil {
		return x.DecorateID
	}
	return 0
}

func (x *RpcChangeGroundReq) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

var File_landrpc_proto protoreflect.FileDescriptor

var file_landrpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x64, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3d, 0x0a, 0x0b, 0x52, 0x50, 0x43, 0x43, 0x69, 0x74, 0x79, 0x54, 0x6f, 0x77, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x77, 0x6e, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f, 0x77, 0x6e, 0x49, 0x44, 0x22,
	0x41, 0x0a, 0x0f, 0x52, 0x50, 0x43, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x54, 0x6f,
	0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f,
	0x77, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f, 0x77, 0x6e,
	0x49, 0x44, 0x22, 0x4c, 0x0a, 0x12, 0x52, 0x50, 0x43, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x54, 0x6f, 0x77, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56,
	0x65, 0x63, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0xf5, 0x01, 0x0a, 0x15, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f,
	0x6c, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x77, 0x6e, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x6f, 0x77, 0x6e, 0x49, 0x44, 0x22, 0xb1, 0x03, 0x0a, 0x0c, 0x52, 0x50, 0x43,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x41, 0x0a, 0x0c, 0x72, 0x6f, 0x6c,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x72, 0x6f, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x64, 0x31, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x31, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x31, 0x12, 0x3b, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x32, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x64, 0x32, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x32, 0x12, 0x2e, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x33, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x64, 0x33, 0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x31, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x3a, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x32, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x01, 0x0a,
	0x0b, 0x52, 0x50, 0x43, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x6f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x6f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x74, 0x6f, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x84, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1b,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x45, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x7c, 0x0a,
	0x12, 0x52, 0x70, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x6e,
	0x64, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x2a, 0x5d, 0x0a, 0x03, 0x45,
	0x4f, 0x70, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4f, 0x50, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4f, 0x50, 0x5f, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4f, 0x50, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x4f, 0x50, 0x5f, 0x44,
	0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4f, 0x50, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55, 0x50, 0x10, 0x04, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_landrpc_proto_rawDescOnce sync.Once
	file_landrpc_proto_rawDescData = file_landrpc_proto_rawDesc
)

func file_landrpc_proto_rawDescGZIP() []byte {
	file_landrpc_proto_rawDescOnce.Do(func() {
		file_landrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_landrpc_proto_rawDescData)
	})
	return file_landrpc_proto_rawDescData
}

var file_landrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_landrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_landrpc_proto_goTypes = []interface{}{
	(EOp)(0),                      // 0: protos.EOp
	(*RPCCityTown)(nil),           // 1: protos.RPCCityTown
	(*RPCCreateInTown)(nil),       // 2: protos.RPCCreateInTown
	(*RPCCreateInTownRsp)(nil),    // 3: protos.RPCCreateInTownRsp
	(*RPCEntityTransferInfo)(nil), // 4: protos.RPCEntityTransferInfo
	(*RPCEntityReq)(nil),          // 5: protos.RPCEntityReq
	(*RPCSpaceReq)(nil),           // 6: protos.RPCSpaceReq
	(*Consume)(nil),               // 7: protos.Consume
	(*RpcChangeGroundReq)(nil),    // 8: protos.RpcChangeGroundReq
	nil,                           // 9: protos.RPCEntityReq.Extend1Entry
	nil,                           // 10: protos.RPCEntityReq.Extend2Entry
	nil,                           // 11: protos.Consume.ItemsEntry
	(*Vec2)(nil),                  // 12: protos.Vec2
	(*anypb.Any)(nil),             // 13: google.protobuf.Any
}
var file_landrpc_proto_depIdxs = []int32{
	12, // 0: protos.RPCCreateInTownRsp.pos:type_name -> protos.Vec2
	4,  // 1: protos.RPCEntityReq.roleTransfer:type_name -> protos.RPCEntityTransferInfo
	9,  // 2: protos.RPCEntityReq.extend1:type_name -> protos.RPCEntityReq.Extend1Entry
	10, // 3: protos.RPCEntityReq.extend2:type_name -> protos.RPCEntityReq.Extend2Entry
	13, // 4: protos.RPCEntityReq.extend3:type_name -> google.protobuf.Any
	5,  // 5: protos.RPCSpaceReq.baseinfo:type_name -> protos.RPCEntityReq
	11, // 6: protos.Consume.items:type_name -> protos.Consume.ItemsEntry
	0,  // 7: protos.Consume.op:type_name -> protos.EOp
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_landrpc_proto_init() }
func file_landrpc_proto_init() {
	if File_landrpc_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_landrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCCityTown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCCreateInTown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCCreateInTownRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEntityTransferInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEntityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_landrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcChangeGroundReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_landrpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_landrpc_proto_goTypes,
		DependencyIndexes: file_landrpc_proto_depIdxs,
		EnumInfos:         file_landrpc_proto_enumTypes,
		MessageInfos:      file_landrpc_proto_msgTypes,
	}.Build()
	File_landrpc_proto = out.File
	file_landrpc_proto_rawDesc = nil
	file_landrpc_proto_goTypes = nil
	file_landrpc_proto_depIdxs = nil
}
