// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: migrate.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Vec3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// CellEntitySourceInfo 迁移的实体源信息
type CellEntitySourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	EntityID    string `protobuf:"bytes,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	EntityLabel string `protobuf:"bytes,3,opt,name=entityLabel,proto3" json:"entityLabel,omitempty"`
	// 该实体所在的base Server id， 如果为""，表示不在任何base server
	FromServerID string            `protobuf:"bytes,4,opt,name=fromServerID,proto3" json:"fromServerID,omitempty"`
	Extra        map[string]string `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CellEntitySourceInfo) Reset() {
	*x = CellEntitySourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellEntitySourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellEntitySourceInfo) ProtoMessage() {}

func (x *CellEntitySourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellEntitySourceInfo.ProtoReflect.Descriptor instead.
func (*CellEntitySourceInfo) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *CellEntitySourceInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CellEntitySourceInfo) GetEntityID() string {
	if x != nil {
		return x.EntityID
	}
	return ""
}

func (x *CellEntitySourceInfo) GetEntityLabel() string {
	if x != nil {
		return x.EntityLabel
	}
	return ""
}

func (x *CellEntitySourceInfo) GetFromServerID() string {
	if x != nil {
		return x.FromServerID
	}
	return ""
}

func (x *CellEntitySourceInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// ReqEnterSpace 请求进入新场景 baseapp -> cellappmgr
type ReqEnterSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceInfo     *CellEntitySourceInfo `protobuf:"bytes,1,opt,name=sourceInfo,proto3" json:"sourceInfo,omitempty"`
	EnterSpaceID   string                `protobuf:"bytes,2,opt,name=enterSpaceID,proto3" json:"enterSpaceID,omitempty"`
	EnterSpaceKind int32                 `protobuf:"varint,3,opt,name=enterSpaceKind,proto3" json:"enterSpaceKind,omitempty"`
	EnterPos       *Vec3                 `protobuf:"bytes,4,opt,name=enterPos,proto3" json:"enterPos,omitempty"`
}

func (x *ReqEnterSpace) Reset() {
	*x = ReqEnterSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEnterSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterSpace) ProtoMessage() {}

func (x *ReqEnterSpace) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterSpace.ProtoReflect.Descriptor instead.
func (*ReqEnterSpace) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{2}
}

func (x *ReqEnterSpace) GetSourceInfo() *CellEntitySourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *ReqEnterSpace) GetEnterSpaceID() string {
	if x != nil {
		return x.EnterSpaceID
	}
	return ""
}

func (x *ReqEnterSpace) GetEnterSpaceKind() int32 {
	if x != nil {
		return x.EnterSpaceKind
	}
	return 0
}

func (x *ReqEnterSpace) GetEnterPos() *Vec3 {
	if x != nil {
		return x.EnterPos
	}
	return nil
}

// EnterSpaceInfo 请求进入场景返回 cellappmgr -> baseapp
type EnterSpaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceServerID  string                `protobuf:"bytes,1,opt,name=SpaceServerID,proto3" json:"SpaceServerID,omitempty"`
	SourceInfo     *CellEntitySourceInfo `protobuf:"bytes,2,opt,name=sourceInfo,proto3" json:"sourceInfo,omitempty"`
	EnterSpaceID   string                `protobuf:"bytes,3,opt,name=enterSpaceID,proto3" json:"enterSpaceID,omitempty"`
	EnterSpaceKind int32                 `protobuf:"varint,4,opt,name=enterSpaceKind,proto3" json:"enterSpaceKind,omitempty"`
	EnterPos       *Vec3                 `protobuf:"bytes,5,opt,name=enterPos,proto3" json:"enterPos,omitempty"`
}

func (x *EnterSpaceInfo) Reset() {
	*x = EnterSpaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSpaceInfo) ProtoMessage() {}

func (x *EnterSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSpaceInfo.ProtoReflect.Descriptor instead.
func (*EnterSpaceInfo) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{3}
}

func (x *EnterSpaceInfo) GetSpaceServerID() string {
	if x != nil {
		return x.SpaceServerID
	}
	return ""
}

func (x *EnterSpaceInfo) GetSourceInfo() *CellEntitySourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *EnterSpaceInfo) GetEnterSpaceID() string {
	if x != nil {
		return x.EnterSpaceID
	}
	return ""
}

func (x *EnterSpaceInfo) GetEnterSpaceKind() int32 {
	if x != nil {
		return x.EnterSpaceKind
	}
	return 0
}

func (x *EnterSpaceInfo) GetEnterPos() *Vec3 {
	if x != nil {
		return x.EnterPos
	}
	return nil
}

// RealEnterSpace 发给 对应的 space app 的消息  baseapp -> cellapp
type RealEnterSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceInfo     *CellEntitySourceInfo `protobuf:"bytes,1,opt,name=sourceInfo,proto3" json:"sourceInfo,omitempty"`
	EntityDatas    []byte                `protobuf:"bytes,2,opt,name=entityDatas,proto3" json:"entityDatas,omitempty"`
	EnterSpaceID   string                `protobuf:"bytes,3,opt,name=enterSpaceID,proto3" json:"enterSpaceID,omitempty"`
	EnterSpaceKind int32                 `protobuf:"varint,4,opt,name=enterSpaceKind,proto3" json:"enterSpaceKind,omitempty"`
	EnterPos       *Vec3                 `protobuf:"bytes,5,opt,name=enterPos,proto3" json:"enterPos,omitempty"`
}

func (x *RealEnterSpace) Reset() {
	*x = RealEnterSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealEnterSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealEnterSpace) ProtoMessage() {}

func (x *RealEnterSpace) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealEnterSpace.ProtoReflect.Descriptor instead.
func (*RealEnterSpace) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{4}
}

func (x *RealEnterSpace) GetSourceInfo() *CellEntitySourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *RealEnterSpace) GetEntityDatas() []byte {
	if x != nil {
		return x.EntityDatas
	}
	return nil
}

func (x *RealEnterSpace) GetEnterSpaceID() string {
	if x != nil {
		return x.EnterSpaceID
	}
	return ""
}

func (x *RealEnterSpace) GetEnterSpaceKind() int32 {
	if x != nil {
		return x.EnterSpaceKind
	}
	return 0
}

func (x *RealEnterSpace) GetEnterPos() *Vec3 {
	if x != nil {
		return x.EnterPos
	}
	return nil
}

// 空间创建完成后的通知
type SpaceLoaded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID string `protobuf:"bytes,1,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	SpaceID  string `protobuf:"bytes,2,opt,name=SpaceID,proto3" json:"SpaceID,omitempty"`
	Kind     int32  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *SpaceLoaded) Reset() {
	*x = SpaceLoaded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceLoaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceLoaded) ProtoMessage() {}

func (x *SpaceLoaded) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceLoaded.ProtoReflect.Descriptor instead.
func (*SpaceLoaded) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{5}
}

func (x *SpaceLoaded) GetServerID() string {
	if x != nil {
		return x.ServerID
	}
	return ""
}

func (x *SpaceLoaded) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *SpaceLoaded) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

type CreateSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceID string            `protobuf:"bytes,1,opt,name=SpaceID,proto3" json:"SpaceID,omitempty"`
	Kind    int32             `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Extra   map[string]string `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CreateSpaceReq) Reset() {
	*x = CreateSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceReq) ProtoMessage() {}

func (x *CreateSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_migrate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceReq.ProtoReflect.Descriptor instead.
func (*CreateSpaceReq) Descriptor() ([]byte, []int) {
	return file_migrate_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSpaceReq) GetSpaceID() string {
	if x != nil {
		return x.SpaceID
	}
	return ""
}

func (x *CreateSpaceReq) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *CreateSpaceReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_migrate_proto protoreflect.FileDescriptor

var file_migrate_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x30, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x33, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x89, 0x02, 0x0a, 0x14, 0x43, 0x65,
	0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x3d, 0x0a, 0x05,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xc3, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63,
	0x33, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x0e,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24,
	0x0a, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x3c, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x28,
	0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x22, 0xe6, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72,
	0x50, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x6f,
	0x73, 0x22, 0x57, 0x0a, 0x0b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x37, 0x0a, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_migrate_proto_rawDescOnce sync.Once
	file_migrate_proto_rawDescData = file_migrate_proto_rawDesc
)

func file_migrate_proto_rawDescGZIP() []byte {
	file_migrate_proto_rawDescOnce.Do(func() {
		file_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_migrate_proto_rawDescData)
	})
	return file_migrate_proto_rawDescData
}

var file_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_migrate_proto_goTypes = []interface{}{
	(*Vec3)(nil),                 // 0: protos.Vec3
	(*CellEntitySourceInfo)(nil), // 1: protos.CellEntitySourceInfo
	(*ReqEnterSpace)(nil),        // 2: protos.ReqEnterSpace
	(*EnterSpaceInfo)(nil),       // 3: protos.EnterSpaceInfo
	(*RealEnterSpace)(nil),       // 4: protos.RealEnterSpace
	(*SpaceLoaded)(nil),          // 5: protos.SpaceLoaded
	(*CreateSpaceReq)(nil),       // 6: protos.CreateSpaceReq
	nil,                          // 7: protos.CellEntitySourceInfo.ExtraEntry
	nil,                          // 8: protos.CreateSpaceReq.ExtraEntry
}
var file_migrate_proto_depIdxs = []int32{
	7, // 0: protos.CellEntitySourceInfo.extra:type_name -> protos.CellEntitySourceInfo.ExtraEntry
	1, // 1: protos.ReqEnterSpace.sourceInfo:type_name -> protos.CellEntitySourceInfo
	0, // 2: protos.ReqEnterSpace.enterPos:type_name -> protos.Vec3
	1, // 3: protos.EnterSpaceInfo.sourceInfo:type_name -> protos.CellEntitySourceInfo
	0, // 4: protos.EnterSpaceInfo.enterPos:type_name -> protos.Vec3
	1, // 5: protos.RealEnterSpace.sourceInfo:type_name -> protos.CellEntitySourceInfo
	0, // 6: protos.RealEnterSpace.enterPos:type_name -> protos.Vec3
	8, // 7: protos.CreateSpaceReq.extra:type_name -> protos.CreateSpaceReq.ExtraEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_migrate_proto_init() }
func file_migrate_proto_init() {
	if File_migrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_migrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellEntitySourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEnterSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterSpaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealEnterSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceLoaded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrate_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_migrate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migrate_proto_goTypes,
		DependencyIndexes: file_migrate_proto_depIdxs,
		MessageInfos:      file_migrate_proto_msgTypes,
	}.Build()
	File_migrate_proto = out.File
	file_migrate_proto_rawDesc = nil
	file_migrate_proto_goTypes = nil
	file_migrate_proto_depIdxs = nil
}
